version: "3"

services:
  mafia-grpc-server:
    image: exponenci/mafia-server:latest
    env_file:
      - .env
    hostname: ${GRPC_HOST}
    ports:
      - "$GRPC_PORT:$GRPC_PORT"
    command:
      python3 main.py

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - .env
    hostname: ${RABBITMQ_HOST}
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_PORT
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  mafia-grpc-client:
    depends_on:
      - mafia-grpc-server
      - rabbitmq
    image: exponenci/mafia-client:latest
    env_file:
      - .env
    volumes:
      - ./outs:/client/outs
    command: # sleep required by running rabbitmq
      python3 test_helpers/run_client.py 
