# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class IServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectClient = channel.unary_unary(
                '/IServer/ConnectClient',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TPingResponse.FromString,
                )
        self.DisconnectClient = channel.unary_unary(
                '/IServer/DisconnectClient',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TPingResponse.FromString,
                )
        self.SubscribeForNotifications = channel.unary_stream(
                '/IServer/SubscribeForNotifications',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TSystemNotification.FromString,
                )
        self.RunGame = channel.unary_unary(
                '/IServer/RunGame',
                request_serializer=server__pb2.TSessionMoveRequest.SerializeToString,
                response_deserializer=server__pb2.TSessionMoveResponse.FromString,
                )


class IServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectClient(self, request, context):
        """по имени и id клиента регистрируем его в нашем сервере 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeForNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunGame(self, request, context):
        """/* по id клиента получаем информацию про его сессию: 
        настройки сессии (кол-во игроков, мафии), статус (жив/мертв) и имена самих игроков*/
        rpc GetSessionInfo(TGetSessionInfoRequest) returns (TGetSessionInfoResponse) {}

        /*по настройкам сессии создается сессия - ей назначается id, 
        клиент получает id сессии*/
        rpc StartSession(TStartSessionRequest) returns (stream TStartSessionResponse) {}

        /* добавить нового клиента в данную сессию 
        сервер уведомляет о новом участнике всем участникам сессии */
        rpc AddMemberToSession(TAddMemberToSessionRequest) returns (stream TAddMemberToSessionResponse) {}

        /* клиент подписывается на уведомления (новые участники+выбор игрока+голосование+тп) по id сессии*/
        rpc SubscribeForNotifications(TSubscribeRequest) returns (stream TNotification) {}

        /* 1 день: говорим о количестве игроков, желаем удачи
        ночь: 
        - мафия просыпается и голосует - сервер собирает голоса и убивает
        - комиссар просыпается и голосует - сервер отвечает кто мафия
        днем:
        - объявляем кто убит - сервер обновляет статусы игроков
        - мирные голосует и объявляем итоги - сервер собирает голоса и убивает одного */
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectClient,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TPingResponse.SerializeToString,
            ),
            'DisconnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectClient,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TPingResponse.SerializeToString,
            ),
            'SubscribeForNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeForNotifications,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TSystemNotification.SerializeToString,
            ),
            'RunGame': grpc.unary_unary_rpc_method_handler(
                    servicer.RunGame,
                    request_deserializer=server__pb2.TSessionMoveRequest.FromString,
                    response_serializer=server__pb2.TSessionMoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/ConnectClient',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/DisconnectClient',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeForNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/IServer/SubscribeForNotifications',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TSystemNotification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/RunGame',
            server__pb2.TSessionMoveRequest.SerializeToString,
            server__pb2.TSessionMoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
