# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class IServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectClient = channel.unary_unary(
                '/IServer/ConnectClient',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TPingResponse.FromString,
                )
        self.WaitInQueue = channel.unary_unary(
                '/IServer/WaitInQueue',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TPingResponse.FromString,
                )
        self.DisconnectClient = channel.unary_unary(
                '/IServer/DisconnectClient',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TPingResponse.FromString,
                )
        self.SubscribeForNotifications = channel.unary_stream(
                '/IServer/SubscribeForNotifications',
                request_serializer=server__pb2.TPingRequest.SerializeToString,
                response_deserializer=server__pb2.TSystemNotification.FromString,
                )
        self.SessionMove = channel.unary_unary(
                '/IServer/SessionMove',
                request_serializer=server__pb2.TSessionMoveRequest.SerializeToString,
                response_deserializer=server__pb2.TSessionMoveResponse.FromString,
                )


class IServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitInQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeForNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectClient,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TPingResponse.SerializeToString,
            ),
            'WaitInQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitInQueue,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TPingResponse.SerializeToString,
            ),
            'DisconnectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectClient,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TPingResponse.SerializeToString,
            ),
            'SubscribeForNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeForNotifications,
                    request_deserializer=server__pb2.TPingRequest.FromString,
                    response_serializer=server__pb2.TSystemNotification.SerializeToString,
            ),
            'SessionMove': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionMove,
                    request_deserializer=server__pb2.TSessionMoveRequest.FromString,
                    response_serializer=server__pb2.TSessionMoveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/ConnectClient',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WaitInQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/WaitInQueue',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/DisconnectClient',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeForNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/IServer/SubscribeForNotifications',
            server__pb2.TPingRequest.SerializeToString,
            server__pb2.TSystemNotification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SessionMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IServer/SessionMove',
            server__pb2.TSessionMoveRequest.SerializeToString,
            server__pb2.TSessionMoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
